### PR TITLE
functional alternative

### PR DESCRIPTION
**Pull request by ahmedk92**
Unfortunately, I can't spot what's causing the crash. Actually, if you try to build your version in release mode, Swift compiler crashes. So, I suspect there's a bug in the Swift compiler. You may submit a bug to their project.

Alternatively, I tried in this PR to provide an alternative approach (albeit functional in style) to solve the problem I understood.

Best of luck!

### CODE REVIEW

**Comment by ahmedAlmasri** [comment]
@ahmedk92  Thank you for your effort, But when using the factory as a `typealias` this is not abstraction lat say we have another converter how to inject it?

**Comment by ahmedk92** [comment]
I don't think understand very well, can you demonstrate with code/pseudocode?

**Comment by ahmedAlmasri** [comment]
let say we need to add a new Factory converter to convert data to the String how to do this?

basically we need to apply Liskov  abstract class and override methods in subclasses with constraint type

**Comment by ahmedAlmasri** [comment]
look it this issue 

https://forums.swift.org/t/method-override-with-a-generic-signature-with-requirements-not-imposed-by-the-base-method/33593/2

**Comment by ahmedk92** [comment]
I think the post you linked already answers your question; that is, it seems what you were trying to do is not possible anymore, unfortunately.

Now, building upon the approach suggested in this PR, what I understand is the feasibility of declaring something like this:

```swift
typealias StringConverter<T: StringProtocol> = Converter<Data, T>
typealias StringConverterFactory<T: StringProtocol> = () -> StringConverter<T>

func makeStringConverter<T>() -> StringConverter<T> {
    { data in
        if let string = String(data: data, encoding: .utf8), let decoded = string as? T {
            return decoded
        } else {
            throw NSError()
        }
    }
}

func makeStringConverterFactory<T>() -> StringConverterFactory<T> {
    {
        makeStringConverter()
    }
}
```

I merely converted your String converter and factory classes to match the alternative style. Does this answer your question?

**Pull request closed without merging**
